version: '2'
services:
  agent:
    image: datadog/agent:latest
    environment:
     - DD_API_KEY
     - DD_APM_ENABLED=true
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /proc/:/host/proc/
      - /cgroup/:/host/sys/fs/cgroup/
      - ./php_fpm.yaml:/conf.d/php_fpm.yaml
    ports:
      - 8125/udp
      - 8126/tcp
    privileged: true
    labels:
      - convox.agent=true
      - convox.balancer=false
